### ISSUE TITLE
Edit/Delete UX for everything

### ISSUE THREAD

**Issue by phil-monroe** [lale-help/lale-help#17]

**Comment by jamesfan** [comment]
See designs below.

**Edit Task Button in the Dashboard**
Beside the disabled _Complete this Task_ button. Takes you to the Edit Task Form below.

![edit-task-dashboard](https://cloud.githubusercontent.com/assets/146020/10258668/ec991938-6914-11e5-884a-905c7bb08b57.png)

**Edit Task Form**

![edit-task-form](https://cloud.githubusercontent.com/assets/146020/10258695/3d8b9230-6915-11e5-9ad1-bf94a76ff504.png)

**Edit Circle Form**
Note the Edit Circle link at the top-right corner of the page (only available to circle admins).

Rather than allowing Working Groups to be deleted (and having to figure out what happens to tasks in those deleted WGs), we allow admins to deactivate/reactivate WGs which simply hides them on the Home Page.

![edit-circle-form](https://cloud.githubusercontent.com/assets/146020/10258701/4b9c8d20-6915-11e5-99d7-6e328bc0c409.png)

**Comment by dottorer** [comment]
Looking good. I was wondering if we should already weave in some of the additional fields in the designs (i.e. more than one helper as in issue 33, date/time and periods for tasks issue 28, etc.

Also, when viewing multiple tasks within on work group, it really gets confusing which data element visually belong to which task. Could we style them so the single task within a WG pops out more clearly (row shading in grid or frame around it or numbering tasks or some sort...).

**Comment by dottorer** [comment]
I think this is mainly all there now and can be closed out.
