### ISSUE TITLE
Helper Profile Page

### ISSUE THREAD

**Issue by phil-monroe** [lale-help/lale-help#19]
- User Picture/Identifier
- Edit account

**Comment by dottorer** [comment]
v1.0 of spec for user profile and account info is here: 

https://docs.google.com/document/d/16RYxX8Gf_VBc9u3I6qwDNtEfS7PrerlJ8Qej4L5NA6s/edit# 

We should see if we can get account info and basic personal data into milestone 1.

**Comment by jamesfan** [comment]
Attaching a design for the Edit Profile page. Note the Edit Profile link at the top-right corner of the page.

![edit-profile](https://cloud.githubusercontent.com/assets/146020/10258621/88317a12-6914-11e5-80d1-191854595b00.png)

**Comment by dottorer** [comment]
Nice. Couple of thoughts:
1. Would we list out the password requirements (min 6 chars, 1 alpha, 1 num or something? Probably not mvp1...
2. the more I think about it, I think we can omit Usernames (e.g. "goofy17") as identifier and go with email address only. I have seen sites with either approach. We would show clear names everywhere since this is a local community effort and we want to eliminate the anonymity, so email address is suitable for login identifier.
3. Is there a standard way to crop a picture into a small version that can be used in a user monicker across the system (as well as mobile)? It will be important to offer the 'face to a name' element to make the site personal...

**Comment by dottorer** [comment]
Since we are adding I18N, should we add the 'language preference' on user profile and leverage this setting to chose a display language? This setting would ideally default to the language of the location of the user / circle.

**Comment by phil-monroe** [comment]
@dottorer: I'm going to plan on language preference being a dropdown next to the country field.

**Comment by dottorer** [comment]
sounds good....

**Comment by dottorer** [comment]
For mvp1, user profile needs to be completed with (as shown in the mockup above):
1. the phone and address block
2. picture upload
3. button to delete account
4. username

We also need a 'Everyone can see my profile' checkbox (on as default) to drive if data can be viewed by other members or not. If public, clicking on a user name anywhere in the system should open up the profile view. Also, if public the member is listed in the public directory.

A user name should be not required, but optional. If chosen, it should appear instead of the full name. Also, the name icon changes from first letters of first/last name to first 2 letters of username.
(sorry this username business is a legal requirement)...

**Comment by dottorer** [comment]
For the sign up we need to track the timestamp when the new user accepted the T&Cs. This is also important if we change T&Cs and expire their acceptance. Then we need to re-capture their ok.

Also, we should track when a new user become member of the circle with a date.

**Comment by dottorer** [comment]
Changing title to reflect work needed. This issue is to create edit / view page for the helper to define their full profile. We also have #89 which will expose a subset of this data to the entire member population for profiles marked public.

**Comment by dottorer** [comment]
@phil-monroe @kristysnet 

I want to ensure this is sufficiently clear and focused in specification for mvp1. Here is what I think we need to do:

1. enhance current 'helper profile' (edit and view)
1.1 instead of "Location", we need to provide a simple address with street, postal code, city and country (see mockup above)
1.2 fix bug that we cannot alter a helpers email right now. It simply flips back to the old value without saving.
1.3 Do not show the 'primary circle' field (but leave its value there as its required). The feature for more circles is not yet backed.
1.4 Add long descr field 'About me' for helper to provide some info on them.

This is then also leveraged in the related #89 .

**Comment by dottorer** [comment]
@kristysnet Couple of things I noticed:
1. the 'about me' field is mandatory but shouldn't (also did not even show a * to mark it required)
2. i think it would be much better UX if the user was shown a view-only version of the profile when they click on the top bar menu item. Then on that page they have a button 'Edit your profile' which takes them to the edit page. Once saved they go back to the view page. That would be consistent and intuitive UX. What do you think? 
3. This would also allow us to separate out the 'Change Email' function later into a separate flow. We already have a 'forgot password' button here...

p.s. changing a users email now works great!

thanks for all your contributions so far already!

**Comment by dottorer** [comment]
@kristysnet The helper page is almost there, but we need to make a few changes still. There are really two distinct things here: 
(a) the helper account page, where they can maintain their data like email and address and such
(b) a public helper profile page that represents the helper to others in the circle. 

Changes required:
1. Currently we show the 'public profile' page when we click the 'Your Profile' menu item. This is not how I intended it, we should display the view page of the entire helper account data. This is only shown to the user themselves and they can verify here what they entered into Lale. So it needs to be a view-only version of the 'edit profile' page.
2. Then there will be a button for 'Edit Profile' and one for 'Reset Password'. When hitting the 'Edit profile' button, we are taken to the edit version of that exact page.
3. One the edit page there will be 2 buttons: one for 'Save' and one for 'Cancel' (with 'Save' styled as a button and 'Cancel' just styled as a link.
4. When saved (or cancelled really) we will display the view-only version of the helper page.
5. Bonus credit: From the view-only helper page we could offer a link saying 'View your public profile') which would then open the Helper public profile that all others would see...

Does this make sense? We can chat later in our call as well...Thanks!

**Comment by phil-monroe** [comment]
Seems to be done to me. @dottorer feel free to reopen if you have any issues.
