### ISSUE TITLE
When joining secondary circle, users is stuck in re-joining primary circle

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#295]
In STG, I had user9@lale.help who is admin in circle8 use the "Find Circle" and then join the circle2. The screen showed that there is a pending invite but not in the newly requested circle but the old one! 

![image](https://cloud.githubusercontent.com/assets/14217285/14616614/6eab1682-05ab-11e6-8589-4d2da8146493.png)

Note: 'Klaus Schroeder' is admin in circle8 not circle 2. 

Now the user9 is completely locked out and cannot re-authenticate to the system. He is always shown the "https://staging.lale.help/public/circles/8/membership_pending" screen.

Two things went wrong: 
- user was already in circle8 and should have joined circle2 newly
- user should always be able to log in to the existing circle

Weird thing: Note that once I am on the 'membership_pending' page, I can no longer go to https://staging.lale.help as it will always route me back to the pending page. This tripped up my demo quite a bit...

**Comment by dottorer** [comment]
@phil-monroe @kristysnet It would be important to unstuck this user9 since he is admin in the circle I did a demo for tonight and that is keen on joining Lale asap. I need to send them the invite link for their testers soon and need to rectify this issue.

**Comment by dottorer** [comment]
Here is the rub: 'Georg Friede' is admin in circle8:

![image](https://cloud.githubusercontent.com/assets/14217285/14617518/c976c298-05ae-11e6-891d-55970dda7bc8.png)
_(note that once someone is admin he can never not be admin per this screen)_

But that very some admin user is joining his own circle somehow causing this buggy situation:
![image](https://cloud.githubusercontent.com/assets/14217285/14617571/fca44938-05ae-11e6-8228-0ba9de5c9190.png)

**Comment by kristysnet** [comment]
@dottorer I looked into this bug this morning. I put in a fix that will ensure this won't happen again (i.e.: only allowing users to join a circle once). I'm still trying to track down how the circle mis-hap happened in the first place and can't duplicate it... Do you know what browser they were using? 

Also, I'm trying to "unstick" the user you mentioned on staging. As far as I can tell (and @phil-monroe can correct me if I'm wrong, but users can only be activated once, not on a per circle basis), is this true? You mentioned circle8 and circle2, can you give me the actual names of those circles? It will help me troubleshoot while looking at the data.

**Comment by dottorer** [comment]
It happened in chrome. I did unstuck the user myself today during testing. Join approval is per circle.

The home curcle was Asyl TK, the new circle Haidhausen.

Thanks a million for fixing it.

**Comment by dottorer** [comment]
@kristysnet Did you see my comment in the PR? If this is sorted, i can close this issue...thanks!

**Comment by kristysnet** [comment]
@dottorer yes, sorry for the delay. I'm still trying to reproduce the issue of the join button joining the wrong circle... I'll let you know if I find anything. However, I went ahead and deleted my pull request, as I no longer think that's a solution to the bug. After looking at the code more closely, I think the main issue is that the user status is not per circle (as I think you intended for it to be). Currently, if an active user joins a circle that needs activation, the user is de-activated until the new circle admin approves them (so they can't login to any circle). The code needs to be reworked so that the activation status is on a per-circle basis. Maybe we should loop @phillipoertel into this, as I think he was involved in setting up the user activation flow.

**Comment by dottorer** [comment]
@kristysnet That's exactly what must have happened! The user actually joined the second circle, but since it required approval, he was marked pending as his overall state. Then when logging into his first main circle, he appeared pending there!

So if approval status is not on a per circle basis, we need to refactor to that and I need to talk to @phillipoertel on what that would entail. But this matches the problem precisely...good find!

**Comment by phillipoertel** [comment]
@kristysnet yes, the pending status is currently on the user, where it should be on the Circle::Role. I had realized this after a day of working on the feature, but we decided we'd leave it as is, since multi-circle memberships didn't seem very likely at the time.

**Comment by kristysnet** [comment]
@dottorer and @phillipoertel is this refactor something you would like me to take care of? I have time this week if needed

**Comment by dottorer** [comment]
@kristysnet I think this is something we need to straighten out before we can let folks sue the multi-circle style which is powerful. If you feel like the direction to make the status by circle is clear, then we should proceed. 

Also note that we look at de-activating / blocking users in #42 which will be by circle as well. So this status model will be by circle and have several states (pending, active, blocked for now). 

If you have questions, we can connect with @phillipoertel as he is working on Lale this and next week.

**Comment by dottorer** [comment]
Assigning from @kristysnet over to @phillipoertel since he will be working on #240 which requires the user state to be on a per circle level. Best to let him do the refactoring in one go...

**Comment by phillipoertel** [comment]
@kristysnet @dottorer Being member of multiple circles now works even when one membership is active, the other still pending. 
I'll do some more testing on Friday (tomorrow is a public holiday) since the changes were quite complex and test coverage is incomplete, then deploy to staging during the day.

**Comment by phillipoertel** [comment]
There's now a review app for testing this: https://lale-help-stg-pr-316.herokuapp.com.
Login with admin@lale.help / Example1234. These credentials will work for all future review apps, btw.

**Comment by phillipoertel** [comment]
@dottorer when testing, please be aware the following issue: after joining a new circle, you'll be redirected to the previous circle; but you can switch to the new circle through the user menu. 
This is due to the current circle being stored in the session. I'm not sure what is affected when I remove the circle id from the session, so I'm waiting for @phil-monroe for feedback.

**Comment by phillipoertel** [comment]
@dottorer delivered on the review app https://lale-help-stg-pr-316.herokuapp.com. Login into any review app with admin@lale.help / Example1234.

**Comment by phillipoertel** [comment]
@dottorer I just fixed the empty status problem on the circle role. Tested it locally with a copy of the production data, active and pending status are now set correctly.

**Comment by dottorer** [comment]
Great - that's good to know.

**Comment by dottorer** [comment]
Closing - this works now.
