### ISSUE TITLE
Merge Var for TASK_ORGANIZER not populated

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#314]
It seems that there is no value in the merge var for TASK_ORGANIZER:

![image](https://cloud.githubusercontent.com/assets/14217285/15067905/f41fdbba-1373-11e6-9b08-82c36cde5db1.png)

Although in the task mailer this is set:

`
 def merge_vars(user, task)
    task = ::TaskPresenter.new(task)
    {
      "FIRST_NAME"            => user.first_name,
      "TASK_TITLE"            => task.name,
      "TASK_DESCRIPTION"      => task.description(length: 100),
      "TASK_DUE_DATE"         => task.scheduling_sentence,
      "TASK_TIME_REQUIRED"    => task.duration_text,
      "TASK_HELPERS_REQUIRED" => task.volunteer_count_required,
      "TASK_URL_MAIN"         => handle_token_url(user.login_token.code, redirect: circle_task_path(task.circle, task)),
      "CIRCLE_NAME"           => task.circle.name,
      "TASK_ORGANIZER"        => task.organizer.try(:name)
    }
`

**Comment by phillipoertel** [comment]
I can't reproduce this error. Both when testing locally (with Mandrill templates enabled, see attachment) and in the Rails console in staging the organizer name is correctly inserted.

I can't find exactly this task on staging though, only two tasks named "Lotsendienst organisieren" (without the - Kopie" suffix). Did you delete or rename it? Do you have an id/link for me?

Maybe the issue was with the templates being cached in Mandrill. Could you try again with exactly this task?

![bildschirmfoto 2016-05-06 um 11 53 13](https://cloud.githubusercontent.com/assets/5188/15070193/13264292-1383-11e6-8832-b13e14dc1fb8.png)

**Comment by dottorer** [comment]
Could not reproduce since. Closing for now...
