### ISSUE TITLE
Helper list no longer shows 'organizers' tab

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#382]
We recently changed this to 2 tabs - one for helpers and one for organizers. This tabbed page seems to have been removed again....can we find it?

**Comment by phillipoertel** [comment]
Maybe you aren't an admin of the circle? When you aren't, the "Helper list" link points to the list of public members, which doesn't have the members/organizers tabs at the moment.

**Comment by dottorer** [comment]
Thats unintended then. The link should always point to the tabbed view. Normal helpers need to see the organizer tab.

Only diff is that on the all helpers tab, admin see all but non admin see only public profiles...

**Comment by phillipoertel** [comment]
@dottorer I started looking into this this morning and fixed it now, testable on staging. 

New questions arise though:

- in the message "Shows {num} of {num} helpers.", {num} always showed the same number ("Shows 6 of 6 helpers"), since there was no pagination and the total number of active users/admins was used for both variables. I now use the numbers to show the actually visible members vs. all members in the circle, so a non-member may get "Shows 4 of 6 helpers" if two members have non-public profiles. Is this Ok? 

- since the member profiles are just one click away, I'd suggest removing some of the less important columns to clean up the page.

- the list of helpers who signed up for a task doesn't hide/anonymize people with private profiles, yet. Should it just print "Hidden User" in the user-badge to non-admins? Or can non-admins even see these tasks?

- if there are other places in the app where we list users we should review those as well, if it's an important feature.

**Comment by dottorer** [comment]
@phillipoertel 

ad 1) "4 of 6 helpers" is the exact right answer for non-admins. Should have done that from the start.
ad 2) agreed - which column would you remove?
ad 3) No, I think the name of a helper is public domain. Only the detailed address info should be concealed.
ad 4) See 3.

Thanks for thinking this through and fixing it up!

**Comment by dottorer** [comment]
LGTM now in STG - thanks !!!
