### ISSUE TITLE
Helper can assign themselves twice to a task

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#384]
In production, I encountered the following:

![image](https://cloud.githubusercontent.com/assets/14217285/16701142/3219a06a-455e-11e6-9c3e-9630dc77182b.png)

Not user what the user did but the timestamp tracked for the self assignment is the same on both entries:
![image](https://cloud.githubusercontent.com/assets/14217285/16701171/58c78b3c-455e-11e6-8968-520364d08215.png)

**Comment by phillipoertel** [comment]
@dottorer I added uniqueness checks for the task and supply roles. Working group and project roles had no uniqueness check, either, so I added those, too.

But: because Rails handles these checks at the Ruby level, not the DB, it's still possible to create two roles for the same user; this can happen when two requests run almost in parallel (Details: https://goo.gl/yI0CgH).
This can be prevented with uniqueness checks at the DB level. They are easy to add as well, but can't be added if the DB already has duplicate records. So that needs to be verified first. 

Which way would you like to go? 
- do Ruby-level checking only (nothing left to be done) or 
- add DB-level checks for task/supply roles
- add DB-level checks for all user roles (supply, task, circle, working_group, project)

I'd estimate the effort for the last option between 2-6h, depending on if staging or production data has to be cleaned up first.

The frontend for this will follow in #385, and will prevent users from directly creating multiple records themselves.

**Comment by phillipoertel** [comment]
Here's a the report of the consistency_fail gem, which tries to detecting missing unique indexes in Rails projects:

```
There are calls to validates_uniqueness_of that aren't backed by unique indexes.
--------------------------------------------------------------------------------
Model               Table Columns
--------------------------------------------------------------------------------
Circle::Role        circle_roles (user_id, role_type, circle_id)
Project             projects (name, working_group_id)
Project::Role       project_roles (user_id, role_type, project_id)
Sponsor             sponsors (name)
Supply::Role        supply_roles (user_id, role_type, supply_id)
Task::Role          task_roles (user_id, role_type, task_id)
User::Identity      user_identities (email)
WorkingGroup        working_groups (name, circle_id)
WorkingGroup::Role  working_group_roles (user_id, role_type, working_group_id)
--------------------------------------------------------------------------------


There are calls to has_one that aren't backed by unique indexes.
--------------------------------------------------------------------------------
Model    Table Columns
--------------------------------------------------------------------------------
Address  users (address_id)
Address  circles (address_id)
User     user_identities (user_id)
--------------------------------------------------------------------------------


There are calls to has_one_with_polymorphic that aren't backed by unique indexes.
--------------------------------------------------------------------------------
Model    Table Columns
--------------------------------------------------------------------------------
Sponsor  file_uploads (uploadable_type, uploadable_id)
--------------------------------------------------------------------------------
```

**Comment by dottorer** [comment]
This is easier discussed tomorrow in person, i think...

**Comment by phillipoertel** [comment]
Unique indices added an deployed/migrated in all environments.

**Comment by dottorer** [comment]
LGTM
