### ISSUE TITLE
Check dependent destroys on object graph

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#386]
When we purge a circle in STG or PROD, we need to guarantee all dependent data in the graph is purged.

* Circle
  * Helpers
    * Comments
    * Project Roles
    * Circle Roles
    * WorkingGroup Roles
    * Task Roles
    * Supply Roles
    * Address
  * WorkingGroup
    * WorkingGroup Roles
    * Documents
    * Tasks
      * Comments
      * Task Roles
    * Supplies
      * Comments
      * Supply Roles
  * Projects
      * Tasks
      * Supplies
  * Documents

**Comment by phillipoertel** [comment]
@dottorer thanks for the dependency listing above.

Re. deleting circle helpers: 
- the helper's circle roles should be destroyed for sure, this is safe as well. 
- a helper could be in multiple circles. It could be safely destroyed if he only in one circle. Checking this is a little extra work, and needs to be written & tested with care, since an error here can cause big (!) trouble. Alternatively we could always leave the users in the DB. In that case the user could still log in, but would get a 404/not found error because the circle is gone. The users could also always be deleted "by hand" in the admin area.

**Comment by phillipoertel** [comment]
@dottorer I added dependent destroys for everything I could find. This also means everything down the relation graph will be deleted, i.e. if you delete a working group all tasks, supplies, projects in it should be deleted. 

I also extended the admin area to have a very basic list of all relevant resources. You could now have some fun in the staging admin area :-)

As of now, no users are deleted, only all their circle-specific roles.

**Comment by dottorer** [comment]
@phillipoertel we need to ensure that we do not delete users in a circle if they are also in another circle. It seems that only users with their primary circle being destroyed should be destroyed.

**Comment by phillipoertel** [comment]
@dottorer would you really delete a user if his primary circle is deleted, but he is still in another one?

**Comment by dottorer** [comment]
I guess the best scenario for multi circle users is to delete the circle but not the user. We then would need to make any of his other circles the primary. If only one circle exists, we can delete the user since as an orphan it make little sense.

Technically this could be too much work. I believe that orphaned users would at login be asked to join another existing circle. I could also hand purge orphans from time to time. 

For now let's leave orphan users for me to hand purge....

**Comment by dottorer** [comment]
Using now for DEMO purge...works.
