### ISSUE TITLE
Layout does not scale equally in Chrome and IE as well as Safari /iOS

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#39]
Need to provide cross-browser compatibility for the layout. In IE the layout stretches wall-to-wall whereas in Chrome it is centered nicely.

**Comment by dottorer** [comment]
![screen shot 2015-11-20 at 11 54 24 am](https://cloud.githubusercontent.com/assets/14217285/11336275/276893ca-91e4-11e5-9df2-4bc989945cfd.png)

Also issues on safari, where the task (+) button was squished. Generally, IE and Chrome render very differently.

**Comment by dottorer** [comment]
This is also an issue on iPad when demoing. The safari bug with the (+) button is preventing from unfolding the drop down menu for tasks / supplies. Also had issues on ipad with drop down for the user profile, so maybe there is a generic glitch here. Anyways, prevents mobile demoes right now.

@stephanerangaya  @posixpascal @jamesfan  Any ideas?

**Comment by posixpascal** [comment]
Looks like the `.icon` class has neither a `width` nor `height` attribute attached. I don't have my iPad available right now, but I could push the required changes in the comments pull request. Gimme a sec.

**Comment by dottorer** [comment]
sweet, we can just merge it with the comments styles.

**Comment by dottorer** [comment]
![image](https://cloud.githubusercontent.com/assets/14217285/12244781/8d998d24-b8a5-11e5-9441-d276181ccbdd.png)

In IE, the left nav labels are not left aligned for some reason, looks really weird...

**Comment by dottorer** [comment]
For iPad: In the top bar, the menu for the user settings does not drop down, also the (+) symbol does not unfolds the 'add task / supply' options, so in general the actions from the top bar are not available in iPad. So right now the user cannot get to update their profile or even to log out!

**Comment by madkap** [comment]
hi @dottorer asked me chime in on this issue. fyi i haven't touched the code since the 1st iteration. 

from just using staging and safari and browsing the code from inspect element. it may be Flex that is giving headaches. Support for `display:flex` in [IE is limited](http://caniuse.com/#search=flex). It may be worth refactoring the styling to just use `floats` and `text-align`, etc.  This may be true with IE labels not left aligning the text. The style for those elements are using flex and it is telling the child elements to `justify-content:space-between` and IE may not know what that is.

With the Ipad. it is using javascript to change the class name. i'd double check the JS.  sidenote: there is a way to use only css and html to toggle the visibility of the dropdown menu. using a checkbox and styling the adjacent sibling. I did it for the [1st version of a toggle](https://github.com/lale-help/lale-help/blob/2df063b653818a045a9f5e8c610c81f0653ad572/app/assets/stylesheets/components/_forms.scss#L89-L130). I built a [quick proof of concept](http://codepen.io/madkap/pen/gPRxKE?editors=110) using only css and html.

**Comment by dottorer** [comment]
@madkap : fantastic research and resolution - thank you for the sample code!

@phil-monroe @posixpascal @tmandke : What would be the best way to get this into the app and replace the current implementation? Any thoughts would be appreciated...

**Comment by phil-monroe** [comment]
@dottorer this brings up a good question: what is the minimum version of IE that we are willing to support? To be honest, I'd prefer IE10+.

**Comment by phil-monroe** [comment]
as for the dropdown's: thanks for the examples @madkap! I'll try them out here soon.

**Comment by dottorer** [comment]
Still some glitches with IE:

1. leftnav not left aligned (see above)
2. images not appearing on some pages or being squished:

![image](https://cloud.githubusercontent.com/assets/14217285/12752732/24d2732a-c9c4-11e5-8cbc-c56aa82528ac.png)

![image](https://cloud.githubusercontent.com/assets/14217285/12752770/4a887088-c9c4-11e5-9dcf-14b43af8aa56.png)

Maybe we can apply some of @madkap 's techniques to get things displayed properly...otherwise we have some critical issues for IE users (which most will be I am afraid).

**Comment by dottorer** [comment]
Assigning to @phil-monroe to see if we can implement madcaps concepts to improve rendering in IE. Right now, it is not usable there which is a critical issue for mvp1 due to our target audience.

**Comment by phil-monroe** [comment]
Turns out it had nothing to do with flexbox... I used a placeholder icon that does not exist in our icon font and that causes IE to puke hard...
