### ISSUE TITLE
Bug: Rollbar 27 - Invalid Auth Token

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#409]
https://rollbar.com/lale-help/lale-help/items/27/

**Comment by phillipoertel** [comment]
@dottorer Rails includes a so-called authenticity_token in every form; they are part it's CSRF protection mechanism. 

We get this error when the token has expired, which I assume happens when the session expires (30 minutes for lale). This could happen

1) if the login form is opened but not submitted within the session expiry time
2) if the browser serves a login page from it's cache which has been generated >= 30 minutes ago.

To investigate further, we could contact grohaj@t-online.de, (s)he had this problem yesterday at 12:40:20 am and should be able to remember the circumstances.

Reason 1) could be mitigated by longer session expiry time, reason 2) by disallowing the browser from caching the login form (easily done with HTTP headers).

**Comment by dottorer** [comment]
On first glance, we should not cache the login form then. Makes no sense if this is causing the token failure. 

Could this also have to do with token in email or is this different?

**Comment by dottorer** [comment]
There is the occasional report by users that clicking on the buttons in an email shows them an error screen. It last happened to Matze during a demo at LRA in July. It would be that this has to do with too many open browser sessions with varying users logged in, but I cannot say for sure. Overall, I will need to provide much more concise replication instructions if it re-occurs.

For now, Let's deploy this change and close it so we can see it go down in our prod system.

**Comment by phillipoertel** [comment]
@dottorer I now handle this exception in the login form (no matter where it came from) and redisplay the login form along with a "please try again" message. That should be less scary than the previously unhandled exception (500 internal server error page).
