### ISSUE TITLE
Bug: Rollbar 37 - undefined method "name" for nil:NilClass

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#410]
https://rollbar.com/lale-help/lale-help/items/37/

**Comment by phillipoertel** [comment]
All errors happened in Project 22: 

![bildschirmfoto 2016-09-19 um 12 21 52](https://cloud.githubusercontent.com/assets/5188/18629084/b6b9b312-7e63-11e6-86db-8e8c331d49c7.png)

This project has no admin (i.e. is `nil`in Ruby terms), so when trying to call #name on the admin in the view, we get this error.

The more interesting question is **why** the project has no admin or how it got lost, I'll investigate that. The reason may be the same as in #398, where we had a similar problem when working groups were saved.

**Comment by phillipoertel** [comment]
Update: the reason for this bug is the one fixed in #398, it just hasn't been deployed to production yet (despite being fixed since Aug 9th). That's embarassing, but since Matze was testing on staging and demo, I forgot and then moved on to another issue.

So a production release will fix this, which I'll do today or tomorrow.

**Comment by dottorer** [comment]
@phillipoertel Great - just missing a deploy then...

**Comment by dottorer** [comment]
Was part of #398 . Closing.
