### ISSUE TITLE
Track helper accreditation

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#411]
Related to #401 we also need to provide for a special case whereby admins can store the helper accreditation ('polizeiliches Führungszeugnis') along with an expiration date. 

See more detailed specification in https://docs.google.com/document/d/1IknDxB-giyJSdq5WJJr7rga48GEQl-nIHg-eNBnVleI/edit#

**Comment by phillipoertel** [comment]
FYI :-)
![bildschirmfoto 2016-09-28 um 17 38 47](https://cloud.githubusercontent.com/assets/5188/18920687/6fd2fb98-85a2-11e6-8b77-9bd247c2717f.png)

**Comment by phillipoertel** [comment]
@dottorer Implemented, please review on staging.

**Comment by dottorer** [comment]
@phillipoertel Tested on STG - looking nice!

From a visual point of view, the dotted/dashed circle outline is too noisy and draw attention. Also, if a circle is not choosing to require accreditation, then all helpers would be dotted. Therefore I would like to use the normal full circle outline for non-accredited helpers (as is today) and use the grey background for accredited users (as you implemented). That should address both visualization needs.

- [ ] change non-accredited user icon to solid outline with white background

It tested access to the profile data for admin, organizer and helper. They all seem to have the correct access in edits and views.

**Comment by phillipoertel** [comment]
@dottorer I changed the dashed user icon outline to a solid one and deployed; can be reviewed on staging. 
I also was able to fix the feature specs, but now other tests fails because of the way test data is generated; unfortunately I need to tackle that in another session. I'm quite confident the system works as expected though, so I could deploy to production on Friday morning if you want.

**Comment by dottorer** [comment]
@phillipoertel Looks great now. We can shore up the test data in the next session...
