### ISSUE TITLE
Issue during new circle creation

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#414]
When Matze created a circle today in DEMO, it was saved twice as number 38 (partial) and 39 (with all data). We should track down what happened and how it got partially saved at first.

Note that he was travelling by train and had spotty WLAN.

Timebox this with an hour at first...

**Comment by phillipoertel** [comment]
@dottorer btw. how about validating that a circle's name must be unique in lale (maybe in combination with the location, if required)? That would have prevented the error in the first place.

**Comment by phillipoertel** [comment]
Some observations / info after debugging:

- circle 38 and 39 are both functional. They have separate, but functional admin records (the user and identity are complete and correctly associated to each other and the circle)
- I assume two requests reached the server independently, otherwise the Rails code wouldn't have created two user identities with the same email address (there's a uniqueness check at the Ruby level). I had added an unique check (index) at the DB level some time ago, but it doesn't seem to be there!! I'll investigate further and fix, also on production, since demo's DB is a clone of it.
- reviewing the code: creating a user with it's identity is one request, and it is wrapped in a DB transaction, like every PUT, POST and PATCH request in lale. So if anything goes wrong and is not handled, all DB queries are rolled back. 
- Creating or joining a circle is a separate, subsequent request, after the user is already created. Right now there's nothing in place to keep a user from "dangling" in the system without circle.

What I'd suggest to do:

1. delete circle 38 and all associated data
1. verify the user_identity uniqueness index is set **in the DB**, on all servers (stg, demo, prd). This would have prevented the duplicate user/identity.
1. consider adding **DB uniqueness index** on circle.name. This would have prevented the duplicate circle.

**Comment by dottorer** [comment]
@phillipoertel I like the 3 suggestions. Makes sense. Only thought is that last time we introduced DB level indexes we had some bugs around that in the app. We need to do thorough testing of it.

**Comment by phillipoertel** [comment]
@dottorer I implemented the suggestions and deployed to staging. Please test the creation of circles where the name already exists, and also changing the circle name to one that already exists.

**Comment by dottorer** [comment]
@phillipoertel Tested both new circle creation and alteration of old circle name to an existing name. Both get correct error of name taken. LGTM.
