### ISSUE TITLE
When closing a project, allow to close all open included tasks and supplies

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#440]
Sometimes a project completes, but the helpers did not yet close all included tasks or supplies. It is very painful to have to go and close our the tasks one by one and then close the project. Better would be:

1. when closing project with open tasks / supplies, ask 'This project still has open tasks or supplies. Do you really want to close them all as well?'
2. Offer "Cancel" and "Continue" option. If continue, close all tasks and supplies that are still open and close also the project.

**Comment by NolanChan** [comment]
@dottorer , just for clarification when you say 'close' do you mean 'complete'?

**Comment by NolanChan** [comment]
Some assumptions I made with my PR:

- I edited the projects#complete action and made sure that whenever this action is called, all incomplete tasks and supplies are also closed. I assume that every time a project is closed, it's associated tasks/supplies must also be closed
- I replaced the javascript alert with a regular rails confirm dialog to ask the user
- Because I'm using the regular rails confirm dialog, I'm unable to edit the buttons to become "cancel" and "continue" unless I use a lot more javascript. If this is desired, I can do it

**Comment by dottorer** [comment]
Yep, by close i meant complete the project. I sometimes use those words interchangeably.

**Comment by dottorer** [comment]
@nolanchan Great, i will check it out and think if we even need the ability to complete a project but have included tasks remain open. If not,  the continue/cancel options in the dialogue might be sufficient.

**Comment by dottorer** [comment]
Pushed to PROD - thanks @NolanChan
