### ISSUE TITLE
Circle Management + Dashboard

### ISSUE THREAD

**Issue by phil-monroe** [lale-help/lale-help#51]
https://docs.google.com/document/d/1jEzrh9tTZ1nHFbQDxGUjk3_0g_6HXfMt2pqb5TzxTbo/edit#heading=h.rfesp1z4wx0q

Relates to:
#48 
#17

**Comment by dottorer** [comment]
Assigning to @phil-monroe since he is working on dashboards for work groups and the whole circle.

**Comment by dottorer** [comment]
![image](https://cloud.githubusercontent.com/assets/14217285/12916053/c9981fd4-cf2f-11e5-86fe-d6556ce30a16.png)

Looking good! Few things to note:
1. I pushed the German translations into the dashboard branch
2. The title says 'Circle Dashboard' and is not translatable. It should like read 'Dashboard for:' + circle name.
3. Circle dashboard does not show open supplies, workgroup dashboards already do.
4. Label 'Need help' is squished to the button
5. on the task / supply line partial:
5.1 the round color circle should be much smaller / lightweight. A third in size would suffice (more like the presence dot in slack, bit larger though).
5.2 There are only 4 states and the colors are: 
- new = #546E7A 
- fully assigned = #263238
- completed = green value we use today for task header
- urgent = a nice red
we do NOT need the orange dot, this will be shown in the text message on the partial.
6. Supplies will have a similar / same partial I assume. For the stats here, I was thinking we need to track not the "number of helpers" but analogous "number of supplies" (so we can ask for 5 pairs of kids shoes and accept from multiple donors. Same donor needs to be able to provide more than one pair). In order to not overload this dashboard issue, I have move the supply stats improvement to another separate issue.
7. Box with circle leaders shows only admins, right? Should it list also WG organizers? I don't think a icon group for all members makes sense as there will be too many and we have the separate listing for it.

@phil-monroe Let me know if you want to chat later today...this is looking real neat though!

**Comment by dottorer** [comment]
@stephanerangaya any better UX wisdom than my outline?

**Comment by dottorer** [comment]
![image](https://cloud.githubusercontent.com/assets/14217285/12955068/a29672e4-d021-11e5-872d-d1f03bfbfb6a.png)

Looking a bit squished on ipad...

**Comment by phil-monroe** [comment]
everything should be cleaned up :smile:
